---
name: UID
version: 0.21
author:
  - 'David Green <plato@cpan.org>'
abstract: Define unique identifier objects that can be used like a kind of keyword
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  UID:
    file: lib/UID.pm
    version: 0.21
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
